### ISSUE TITLE
[Feature Request] Integration with ESPHome

### ISSUE THREAD

**Issue by ajayjohn** [SinisterRj/Octoprint_SafetyPrinter#2]
This is a fantastic idea. Thank you for making this plugin.
Could you please add support for ESPHome as it allows a much wider variety of sensors and better OTA management? https://esphome.io/components/api.html

**Comment by SinisterRj** [comment]
Hello AJ, I am glad that you liked it! About ESPHome i don't have any experience with that, but I think it has the same problem of the MQTT proposed here: [https://community.octoprint.org/t/looking-for-beta-testers-safety-printer/34823/10?u=sinisterrj](https://community.octoprint.org/t/looking-for-beta-testers-safety-printer/34823/10?u=sinisterrj)

As a safety system we want to keep it as simple as possible to increase its reliability and despite these new home automation protocols are powerfull and easy to implement, they are complex and depends on many stuff to work. So, in our specific application is better to use the old reliable wiring.

**Comment by ajayjohn** [comment]
I don't quite agree with the view you shared and believe that this choice should be left to the user (who may have other failsafes coded into their home automation system). Especially cause I wasn't referring to a connection via MQTT, but rather via the direct native API ESPHome provides. I understand the loss of network connectivity could be a potential risk here, but there is where there could be failsafes coded into a platform like Home Assistant.

However, I do respect your view and wish you all the best with this project. Thanks!
