### ISSUE TITLE
Can not connect to printer

### ISSUE THREAD

**Issue by jerrychen100d** [SinisterRj/Octoprint_SafetyPrinter#3]
Just installed the plugin and got an error when trying to connect to the printer (Creality Ender 3).
Are there other plugins that might interfere with this plugin?

Let me know what logs you need.

Here's the screenshot of the error
![image](https://user-images.githubusercontent.com/11529335/132261883-a46261a5-8fff-4be2-9f92-c41634a94db6.png)

And here's the list of plugin I current have downloaded.
[
  {
    "url": "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress",
    "name": "DisplayLayerProgress Plugin",
    "key": "DisplayLayerProgress"
  },
  {
    "url": "https://github.com/kantlivelong/OctoPrint-PSUControl",
    "name": "PSU Control",
    "key": "psucontrol"
  },
  {
    "url": "https://github.com/ntoff/OctoPrint-Estop",
    "name": "Emergency Stop Button",
    "key": "estop"
  },
  {
    "url": "https://github.com/Renaud11232/OctoPrint-Resource-Monitor",
    "name": "Resource Monitor",
    "key": "resource_monitor"
  },
  {
    "url": "https://github.com/SinisterRj/Octoprint_SafetyPrinter",
    "name": "Safety Printer",
    "key": "SafetyPrinter"
  },
  {
    "url": "https://github.com/j7126/OctoPrint-Dashboard",
    "name": "Dashboard",
    "key": "dashboard"
  }
]

**Comment by SinisterRj** [comment]
Hello @jerrychen100d

The plugin is new, and I don't have any notice about another plugins interference. Probably your octoprint is tring to connect to the Safety Printer MCU thinking that it is your printer. Try to follow this tutorial and checks if it solves the problem: [https://github.com/SinisterRj/SafetyPrinter/wiki/Solve-connection-problems](https://github.com/SinisterRj/SafetyPrinter/wiki/Solve-connection-problems).

IF not, please send me the safety printer log file. You can download it from your Octoprint interface navigating to the to the Settings tab (the wrench icon at the top of the page), then "Logging", find "plugin_SafetyPrinter_console.log" and click on "download icon" next to it on "Action" column.

**Comment by jerrychen100d** [comment]
Does the plugin work with factory hardware?
Meaning, does the plugin works without having to assemble the Safety Print MCU electronics?

If so, apologies ahead of times as I had the impression that this was going to work with stock hardware 😂

**Comment by SinisterRj** [comment]
Sorry, but no. The plugin is just the interface. You need an Arduino with Safety Printer MCU firmware flashed on it to work.

Em 8 de set. de 2021, à(s) 00:08, hsincc ***@***.***> escreveu:

﻿

Does the plugin work with factory hardware?
Meaning, does the plugin works without having to assemble the Safety Print MCU electronics?

If so, apologies ahead of times as I had the impression that this was going to work with stock hardware 😂

**Comment by SinisterRj** [comment]
Here you can find the Schematics and the source code of the firmware: [Safety Printer](https://github.com/SinisterRj/SafetyPrinter)
