### ISSUE TITLE
Feature Request: Add support for PSUControl to allow switch off and on when not tripped

### ISSUE THREAD

**Issue by ivebeenlinuxed** [SinisterRj/Octoprint_SafetyPrinter#6]
Currently the feature "Shutdown after print" shows that there is a need for a user controlled shutdown and power on - as long as the safety features have not been tripped.

These features are also in the PSUControl plugin, which extends these functions further. The PSUControl plugin is supported natively in apps, such as the Android app "OctoApp" for Android.

This request is that the Shutdown functionality and other power up functionalities (which are not safety related) are made compatible with the PSUControl plugin, to extend this functionality further.

**Comment by SinisterRj** [comment]
Added comand <r7>. Check the "devel" branch.
